class Sessions:
    def __init__(self):
        self.for_anger = "Recommended session:\n\nStart with Cleansing Breaths:\n    * Sit comfortably with your spine straight.\n    * Close your eyes and take deep breaths in through your nose and out through your mouth.\n    * Visualize breathing in fresh, clean air and exhaling any negative feelings.\n\nBalasana which is also known as Child's Pose will soothe your mind and body.\n    * Kneel on the floor with your big toes touching and knees apart.\n    * Sit back on your heels and extend your arms forward on the floor.\n    * Rest your forehead on the mat and breathe deeply.\n    * Hold for 1-3 minutes.\n\nMarjaryasana-Bitilasana also known as Cat-Cow-Pose will relieve the stress and calm the mind.\n    * Begin on your hands and knees in a tabletop position.\n    * Inhale as you arch your back (Cow Pose) and exhale as you round your spine (Cat Pose).\n    * Repeat for 1-2 minutes.\n\nUttanasana will help you with your currrent mood.\n    * Stand with your feet hip-width apart.\n    * Inhale and raise your arms overhead, then exhale and bend forward at your hips, letting your arms hang down.\n    * Keep your knees slightly bent and relax your neck.\n    * Hold for 1-2 minutes.\n\nRemember to move slowly and mindfully through each pose, focusing on your breath and letting go of any tension."

        self.for_disgust = "Recommended session:\n\nStart with Cleansing Breaths:\n    * Sit comfortably with your spine straight.\n    * Close your eyes and take deep breaths in through your nose and out through your mouth.\n    * Visualize breathing in fresh, clean air and exhaling any negative feelings.\n\nSeated Forward Bend (Paschimottanasana):\n    * Sit with your legs extended straight in front of you.\n    * Inhale and lengthen your spine, then exhale and fold forward, reaching for your feet.\n    * Hold this pose for 1-2 minutes, focusing on releasing tension and negative energy.\n\nSpinal Twist (Ardha Matsyendrasana): \n    * Sit with your legs extended, then bend your right knee and place your right foot outside your left thigh.\n    * Inhale and lengthen your spine, then exhale and twist to the right, placing your left elbow outside your right knee.\n    * Hold for 30 seconds to 1 minute, then switch sides.\n\nBridge Pose (Setu Bandhasana): \n    * Lie on your back with your knees bent and feet flat on the floor, hip-width apart.\n    * Inhale and lift your hips towards the ceiling, pressing your feet and arms into the mat.\n    * Hold for 30 seconds to 1 minute, breathing deeply.\n\nCorpse Pose (Savasana):\n    *Lie flat on your back with your legs extended and arms by your sides, palms facing up.\n    * Close your eyes and focus on your breath.\n    * Stay in this pose for 5-10 minutes, allowing your body to completely relax.\n\nFinish with a Visualization Meditation: \n  * While in Savasana, visualize a clean, pure light entering your body with each inhale.\n  * Imagine this light cleansing away any feelings of disgust, leaving you feeling fresh and renewed.\n\nThis session aims to create a sense of release and renewal, helping you move past the feeling of disgust. Remember to move gently and mindfully through each pose, focusing on your breath and your intention to cleanse and let go."

        self.for_sad = "Recommended session:\n\nStart with Cleansing Breaths:\n    * Sit comfortably with your spine straight.\n    * Close your eyes and take deep breaths in through your nose and out through your mouth.\n    * Visualize breathing in fresh, clean air and exhaling any negative feelings.\n\nBalasana which is also known as Child's Pose will soothe your mind and body.\n    * Kneel on the floor with your big toes touching and knees apart.\n    * Sit back on your heels and extend your arms forward on the floor.\n    * Rest your forehead on the mat and breathe deeply.\n    * Hold for 1-3 minutes.\n\nSeated Forward Bend (Paschimottanasana):\n    * Sit with your legs extended straight in front of you.\n    * Inhale and lengthen your spine, then exhale and fold forward, reaching for your feet.\n    * Hold this pose for 1-2 minutes, focusing on releasing tension and negative energy.\n\nMarjaryasana-Bitilasana also known as Cat-Cow-Pose will relieve the stress and calm the mind.\n    * Begin on your hands and knees in a tabletop position.\n    * Inhale as you arch your back (Cow Pose) and exhale as you round your spine (Cat Pose).\n    * Repeat for 1-2 minutes.\n\nCorpse Pose (Savasana):\n    *Lie flat on your back with your legs extended and arms by your sides, palms facing up.\n    * Close your eyes and focus on your breath.\n    * Stay in this pose for 5-10 minutes, allowing your body to completely relax.\n\nFinish with a Gratitude Meditation:\n    * While in Savasana, think of three things you are grateful for. They can be big or small.\n    * Focus on the feeling of gratitude and let it fill your heart and mind.\n\nThis yoga session is designed to help you release sadness and find a sense of calm and gratitude. Remember to move gently and mindfully through each pose, and give yourself the space to feel and release your emotions."

        self.for_fear = "Recommended session:\n\nStart with Grounding Breaths:\n    * Sit comfortably with your spine straight.\n    * Close your eyes and take deep breaths in through your nose and out through your mouth.\n    * Visualize breathing in fresh, clean air and exhaling any negative feelings.\n\nMountain Pose (Tadasana):\n    * Stand tall with your feet together or hip-width apart.\n    * Press your feet firmly into the ground and engage your thighs.\n    * Inhale and reach your arms overhead, lifting through your chest.\n    * Hold for 1-2 minutes, focusing on your breath and the stability beneath your feet.\n\nBalasana which is also known as Child's Pose will soothe your mind and body.\n    * Kneel on the floor with your big toes touching and knees apart.\n    * Sit back on your heels and extend your arms forward on the floor.\n    * Rest your forehead on the mat and breathe deeply.\n    * Hold for 1-3 minutes.\n\nMarjaryasana-Bitilasana also known as Cat-Cow-Pose will relieve the stress and calm the mind.\n    * Begin on your hands and knees in a tabletop position.\n    * Inhale as you arch your back (Cow Pose) and exhale as you round your spine (Cat Pose).\n    * Repeat for 1-2 minutes.\n\nCorpse Pose (Savasana):\n    *Lie flat on your back with your legs extended and arms by your sides, palms facing up.\n    * Close your eyes and focus on your breath.\n    * Stay in this pose for 5-10 minutes, allowing your body to completely relax.\n\nFinish with a Safety Visualization:\n    * While in Savasana, visualize a warm, protective light surrounding you.\n    * Imagine this light creating a safe and calm space where fear cannot enter.\n\nThis yoga session is designed to help you feel grounded and protected. Remember to move gently and mindfully through each pose, and give yourself permission to feel and release your emotions."

        self.for_other = "Recommended session:\n\nStart with Grounding Breaths:\n    * Sit comfortably with your spine straight.\n    * Close your eyes and take deep breaths in through your nose and out through your mouth.\n    * Visualize breathing in fresh, clean air and exhaling any negative feelings.\n\nCat-Cow Pose (Marjaryasana-Bitilasana):\n    * Begin on your hands and knees in a tabletop position.\n    * Inhale as you arch your back (Cow Pose) and exhale as you round your spine (Cat Pose).\n    * Repeat for 1-2 minutes, focusing on the movement and breath.\n\nDownward-Facing Dog (Adho Mukha Svanasana):\n    * From tabletop, tuck your toes under and lift your hips towards the ceiling, forming an inverted V-shape.\n    * Spread your fingers wide and press into your hands, allowing your spine to lengthen.\n    * Hold for 1-2 minutes, taking deep breaths.\n\nWarrior II (Virabhadrasana II):\n    * From Downward Dog, step your right foot forward between your hands.\n    * Turn your left foot out and rise up, extending your arms out to the sides.\n    * Bend your right knee and gaze over your right hand.\n    * Hold for 30 seconds to 1 minute, then switch sides.\n\nCorpse Pose (Savasana):\n    * Lie flat on your back with your legs extended and arms by your sides, palms facing up.\n    * Close your eyes and focus on your breath.\n    * Stay in this pose for 5-10 minutes, allowing your body to completely relax."

        self.mood2session = {
            "angry": self.for_anger,
            "disgust": self.for_disgust,
            "sad": self.for_sad,
            "fearful": self.for_fear,
            "other": self.for_other
        }

sessions = Sessions()
